export const infoProducts = [
    {
        id: 4,
        name_product: "Chaqueta Deportiva Hombre",
        price: 600,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1672675204/Ropa/Chaqueta_Deportiva_Hombre_Zoom_ict9eg.webp",
        category: {
            id: 1,
            name_category: "Ropa",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685044666/Ropa/category_wdzo8w.jpg",
        },
    },
    {
        id: 22,
        name_product: "Pinza amperimetrica digital",
        price: 100,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1672935322/Contruccion/Pinza_amperim%C3%A9trica_digital_Uni-T_UT200A_200A_anjwth.webp",
        category: {
            id: 2,
            name_category: "Otros",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685046578/Contruccion/asdasd_gvetqz.png",
        },
    },
    {
        id: 23,
        name_product: "Almohadas clasicas",
        price: 200,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662067742/ecommerce-colchones-ava/Almohadas/2_nzoyuv.png",
        category: {
            id: 2,
            name_category: "Otros",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685046578/Contruccion/asdasd_gvetqz.png",
        },
    },
    {
        id: 24,
        name_product: "Sabanas para cama doble",
        price: 300,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662068720/ecommerce-colchones-ava/Sabanas/3_pwwedc.png",
        category: {
            id: 2,
            name_category: "Otros",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685046578/Contruccion/asdasd_gvetqz.png",
        },
    },
    {
        id: 5,
        name_product: "Tenis Golty Active Track",
        price: 590,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1672675205/Ropa/Tenis_Golty_Active_Track_tbc1hk.webp",
        category: {
            id: 1,
            name_category: "Ropa",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685044666/Ropa/category_wdzo8w.jpg",
        },
    },
    {
        id: 9,
        name_product: "Diademas  para pc",
        price: 200,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1664403247/ecommerce_tecnology/Categorias/Diademas_w3c0jr.svg",
        category: {
            id: 2,
            name_category: "Tecnologia",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685045127/ecommerce_tecnology/Categorias/O7FJVOLHIF7A43K5PYJOLXWJ4U_ntrovk.jpg",
        },
    },
    {
        id: 10,
        name_product: "Morrales multi uso pc",
        price: 270,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1664403247/ecommerce_tecnology/Categorias/Morrales_da7zk4.svg",
        category: {
            id: 2,
            name_category: "Tecnologia",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685045127/ecommerce_tecnology/Categorias/O7FJVOLHIF7A43K5PYJOLXWJ4U_ntrovk.jpg",
        },
    },
    {
        id: 17,
        name_product: "camion moeljm",
        price: 150,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685046060/Juguetes/camion_moeljm.jpg",
        category: {
            id: 2,
            name_category: "Juguetes",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685046283/Juguetes/juguetes_cxnin7.jpg",
        },
    },
    {
        id: 18,
        name_product: "rompecabezas",
        price: 50,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685046060/Juguetes/rompecabezas_pjnoti.jpg",
        category: {
            id: 2,
            name_category: "Juguetes",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066689/ecommerce-colchones-ava/Muebles/10_jioqti.png",
        },
    },
    {
        id: 19,
        name_product: "coleccion de lego",
        price: 800,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685046060/Juguetes/coleccion_lego_txvapn.jpg",
        category: {
            id: 2,
            name_category: "Juguetes",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066689/ecommerce-colchones-ava/Muebles/10_jioqti.png",
        },
    },
    {
        id: 11,
        name_product: "Silla sofa extendible",
        price: 1270,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066689/ecommerce-colchones-ava/Muebles/9_nqedtx.png",
        category: {
            id: 2,
            name_category: "Muebles",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066689/ecommerce-colchones-ava/Muebles/10_jioqti.png",
        },
    },
    {
        id: 12,
        name_product: "Silla sofa en L",
        price: 1570,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066688/ecommerce-colchones-ava/Muebles/8_ohwrne.png",
        category: {
            id: 2,
            name_category: "Muebles",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066689/ecommerce-colchones-ava/Muebles/10_jioqti.png",
        },
    },
    {
        id: 13,
        name_product: "Sofa hogar blanco",
        price: 1270,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066688/ecommerce-colchones-ava/Muebles/7_cphj37.png",
        category: {
            id: 2,
            name_category: "Muebles",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066689/ecommerce-colchones-ava/Muebles/10_jioqti.png",
        },
    },
    {
        id: 14,
        name_product: "sofa con almuadas",
        price: 1070,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066688/ecommerce-colchones-ava/Muebles/6_zodigr.png",
        category: {
            id: 2,
            name_category: "Muebles",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066689/ecommerce-colchones-ava/Muebles/10_jioqti.png",
        },
    },
    {
        id: 15,
        name_product: "mueble para sala",
        price: 800,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066688/ecommerce-colchones-ava/Muebles/3_lclvff.png",
        category: {
            id: 2,
            name_category: "Muebles",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066689/ecommerce-colchones-ava/Muebles/10_jioqti.png",
        },
    },
    {
        id: 1,
        name_product: "Pack X3 Camisetas Deportivas Originales",
        price: 590,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1672675205/Ropa/Pack_X3_Camisetas_Deportivas_Originales_Ripple_p12jdx.webp",
        category: {
            id: 1,
            name_category: "Ropa",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685044666/Ropa/category_wdzo8w.jpg",
        },
    },
    {
        id: 2,
        name_product: "Camisetas Clasicas Para Hombre",
        price: 400,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1672675205/Ropa/3_Camisetas_B%C3%A1sicas_Para_Hombre_100_En_Algod%C3%B3n_Suavizado_murbg3.webp",
        category: {
            id: 1,
            name_category: "Ropa",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685044666/Ropa/category_wdzo8w.jpg",
        },
    },
    {
        id: 3,
        name_product: "Jean Skinny Lec Lee Para Muje",
        price: 300,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1672675205/Ropa/Jean_Skinny_Lec_Lee_Para_Mujer_-_%C3%8Dndigo_Medio_wnsntu.webp",
        category: {
            id: 1,
            name_category: "Ropa",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685044666/Ropa/category_wdzo8w.jpg",
        },
    },
    {
        id: 16,
        name_product: "peluche pepa",
        price: 100,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685046060/Juguetes/peluche_pepa_sysuft.jpg",
        category: {
            id: 2,
            name_category: "Juguetes",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685046283/Juguetes/juguetes_cxnin7.jpg",
        },
    },
    {
        id: 20,
        name_product: "Carros a control remoto",
        price: 50,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685046060/Juguetes/carros_de_colleccion_dvfegk.jpg",
        category: {
            id: 2,
            name_category: "Juguetes",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1662066689/ecommerce-colchones-ava/Muebles/10_jioqti.png",
        },
    },
    {
        id: 6,
        name_product: "Audifonos inalambricos",
        price: 790,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1664403247/ecommerce_tecnology/Categorias/Audifonos_inalambricos_oqmcte.svgp",
        category: {
            id: 2,
            name_category: "Tecnologia",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685045127/ecommerce_tecnology/Categorias/O7FJVOLHIF7A43K5PYJOLXWJ4U_ntrovk.jpg",
        },
    },
    {
        id: 7,
        name_product: "Cargador para Celular",
        price: 120,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1664403247/ecommerce_tecnology/Categorias/https://res.cloudinary.com/cloudmulti/image/upload/v1664403247/ecommerce_tecnology/Categorias/Cargador_para_Celular_fgqxf6.svg_fgqxf6.svg",
        category: {
            id: 2,
            name_category: "Tecnologia",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685045127/ecommerce_tecnology/Categorias/O7FJVOLHIF7A43K5PYJOLXWJ4U_ntrovk.jpg",
        },
    },
    {
        id: 8,
        name_product: "Parlantes pe3n0h",
        price: 290,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1664403247/ecommerce_tecnology/Categorias/Parlantes_pe3n0h.svg",
        category: {
            id: 2,
            name_category: "Tecnologia",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685045127/ecommerce_tecnology/Categorias/O7FJVOLHIF7A43K5PYJOLXWJ4U_ntrovk.jpg",
        },
    },
    {
        id: 21,
        name_product: "Bicicleta Mountain_bike_Roadmaster",
        price: 1000,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1672934339/Deportes%20y%20Fitness/Mountain_bike_Roadmaster_Wind_R29_24v_zqhu32.webp",
        category: {
            id: 2,
            name_category: "Otros",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685046578/Contruccion/asdasd_gvetqz.png",
        },
    },
    {
        id: 25,
        name_product: "Kit De Pesas Ejercicio Mancuernas",
        price: 7000,
        description: "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
        image: "https://res.cloudinary.com/cloudmulti/image/upload/v1672934339/Deportes%20y%20Fitness/Kit_De_Pesas_Ejercicio_Mancuernas_Juego_De_Pesas_lmxsvp.webp",
        category: {
            id: 2,
            name_category: "Otros",
            image: "https://res.cloudinary.com/cloudmulti/image/upload/v1685046578/Contruccion/asdasd_gvetqz.png",
        },
    }
]